In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

In [11]:
import pandas as pd

df = pd.read_csv('/Exam_Score_Prediction.csv')
df.head()

,student_id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,1,17,male,diploma,2.78,92.9,yes,7.4,poor,coaching,low,hard,58.9
1,2,23,other,bca,3.37,64.8,yes,4.6,average,online videos,medium,moderate,54.8
2,3,22,male,b.sc,7.88,76.8,yes,8.5,poor,coaching,high,moderate,90.3
3,4,20,other,diploma,0.67,48.4,yes,5.8,average,online videos,low,moderate,29.7
4,5,20,female,diploma,0.89,71.6,yes,9.8,poor,coaching,low,moderate,43.7

In [12]:
df.head()

,student_id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,1,17,male,diploma,2.78,92.9,yes,7.4,poor,coaching,low,hard,58.9
1,2,23,other,bca,3.37,64.8,yes,4.6,average,online videos,medium,moderate,54.8
2,3,22,male,b.sc,7.88,76.8,yes,8.5,poor,coaching,high,moderate,90.3
3,4,20,other,diploma,0.67,48.4,yes,5.8,average,online videos,low,moderate,29.7
4,5,20,female,diploma,0.89,71.6,yes,9.8,poor,coaching,low,moderate,43.7

In [14]:
df.shape

(20000, 13)

In [15]:
df.columns

Index(['student_id', 'age', 'gender', 'course', 'study_hours',
       'class_attendance', 'internet_access', 'sleep_hours', 'sleep_quality',
       'study_method', 'facility_rating', 'exam_difficulty', 'exam_score'],
      dtype='object')

In [16]:
X = df[['study_hours',
        'class_attendance',
        'sleep_hours',
        'sleep_quality',
        'study_method',
        'exam_difficulty',
        'facility_rating']]

y = df['exam_score']

In [17]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X.head()

X shape: (20000, 7)
y shape: (20000,)

,study_hours,class_attendance,sleep_hours,sleep_quality,study_method,exam_difficulty,facility_rating
0,2.78,92.9,7.4,poor,coaching,hard,low
1,3.37,64.8,4.6,average,online videos,moderate,medium
2,7.88,76.8,8.5,poor,coaching,moderate,high
3,0.67,48.4,5.8,average,online videos,moderate,low
4,0.89,71.6,9.8,poor,coaching,moderate,low

In [21]:
X.shape, y.shape

((20000, 7), (20000,))

In [22]:
df.isnull().sum()

student_id          0
age                 0
gender              0
course              0
study_hours         0
class_attendance    0
internet_access     0
sleep_hours         0
sleep_quality       0
study_method        0
facility_rating     0
exam_difficulty     0
exam_score          0
dtype: int64

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df = df.drop_duplicates()

In [26]:
X.dtypes

study_hours         float64
class_attendance    float64
sleep_hours         float64
sleep_quality        object
study_method         object
exam_difficulty      object
facility_rating      object
dtype: object

In [27]:
X = pd.get_dummies(X, drop_first=True, dtype=int)

In [28]:
X.head()

,study_hours,class_attendance,sleep_hours,sleep_quality_good,sleep_quality_poor,study_method_group study,study_method_mixed,study_method_online videos,study_method_self-study,exam_difficulty_hard,exam_difficulty_moderate,facility_rating_low,facility_rating_medium
0,2.78,92.9,7.4,0,1,0,0,0,0,1,0,1,0
1,3.37,64.8,4.6,0,0,0,0,1,0,0,1,0,1
2,7.88,76.8,8.5,0,1,0,0,0,0,0,1,0,0
3,0.67,48.4,5.8,0,0,0,0,1,0,0,1,1,0
4,0.89,71.6,9.8,0,1,0,0,0,0,0,1,1,0

In [29]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [30]:
print(X_train.shape)
print(X_test.shape)

(16000, 13)
(4000, 13)

In [31]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [32]:
y_pred = model.predict(X_test)

print(y_pred[:5])

[ 36.71069872  80.1710026   54.30771469 102.22939739  80.62948565]

In [33]:
from sklearn.metrics import mean_absolute_error, r2_score

print("Actual marks:", y_test[:5].values)
print("Predicted marks:", y_pred[:5])

print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

Actual marks: [ 31.1  81.6  68.  100.   84.8]
Predicted marks: [ 36.71069872  80.1710026   54.30771469 102.22939739  80.62948565]
Mean Absolute Error: 7.862804850781285
R2 Score: 0.7331115596690307

In [34]:
new_student = X_test.iloc[[0]]

prediction = model.predict(new_student)

print("Predicted exam score:", prediction[0])

Predicted exam score: 36.710698719766434